import React from 'react';

const SinglePost = ({ title, creator, ai, timestamp, poem, hash}) => {
    var date = new Date(timestamp);
    var dateOnly = new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    }).format(date);

    return(
        <div className='post' id={hash}>
            <h1 id="title">{title}</h1>
            <h2 id="credits">Generated by {creator} with {ai}</h2>
            <h3 id="date">{dateOnly}</h3>
            <h3 id="contents">{poem}</h3>
            {/*TODO: Add a share link button*/}
        </div>
       
    )
}

export default SinglePost;