import React, {useRef} from 'react';
import icon from './share.ico';

const SinglePost = ({ title, creator, ai, timestamp, poem, hash}) => {
    var date = new Date(timestamp);
    console.log(date);
    console.log(timestamp);
    var dateOnly = new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    }).format(date);

    const linkTextRef = useRef(null);

    function shareClicked() { // Rename the function to shareClicked
        const linkText = linkTextRef.current; // Get the link text element

        const link = new URL(window.location.href).toString() + 'post/?hash=' + hash;

        console.log(linkText.style.display);
        if (linkText.style.display === 'block') { // If the element is currently hidden
            linkText.style.display = 'none'; // Hide the element
          linkText.style.overflowX = 'hidden';
        } else { // If the element is currently visible
            console.log("passed none");
            linkText.style.display = 'block'; // Show the element
          linkText.textContent = link; // Set the text content to the current URL
          linkText.style.overflowX = 'scroll';
            
        }
    }

    function formatPoem({ poem }) {
        console.log(poem);
        return (<div dangerouslySetInnerHTML={{ __html: poem }} />);
    };

    return(
        <div className='post' id={hash}>
            <h1 id="title">{title}</h1>
            <h2 id="credits">Generated by {creator} with {ai}</h2>
            <h3 id="date">{dateOnly}</h3>
            <h3 id="contents">{formatPoem({poem})}</h3>
            <button className="icon" type="button" onClick={shareClicked}>
                <img src={icon} alt="share" />
            </button>
            <div className="link-text" ref={linkTextRef}>{}</div>
        </div>
       
    );
}

export default SinglePost;